### ISSUE TITLE
pull access denied

### ISSUE THREAD

**Issue by Shane01638** [balena-io-playground/photo-slideshow#9]
I have tried using the button and using the CLI and I can't get past "pull access denied".  Using raspberry pi 4b.  I wiped my magicmirror2 build for this and am now regretting that decision lol.

PS C:\Balena\photo-slideshow-master> balena push photo-slideshow
[Info]           Starting build for photo-slideshow, user g_shane_zirkle
[Info]           Dashboard link: https://dashboard.balena-cloud.com/apps/1994895/devices
[Info]           Building on arm05
[Info]           No suitable previous release for caching, skipping cache pull
[kiosk]          Step 1/1 : FROM bh.cr/balenablocks/browser-aarch64/2.4.2
[photo-gallery]  Step 1/1 : FROM bh.cr/balenablocks/photo-gallery-aarch64/0.0.3
[kiosk]          pull access denied for bh.cr/balenablocks/browser-aarch64/2.4.2, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[photo-gallery]  pull access denied for bh.cr/balenablocks/photo-gallery-aarch64/0.0.3, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[Error]          Some services failed to build:
[Error]            Service: photo-gallery
[Error]              Error: pull access denied for bh.cr/balenablocks/photo-gallery-aarch64/0.0.3, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[Error]            Service: kiosk
[Error]              Error: pull access denied for bh.cr/balenablocks/browser-aarch64/2.4.2, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
[Info]           Built on arm05
[Error]          Not deploying release.
Remote build failed

**Comment by maggie44** [comment]
Could you try this one: https://github.com/balena-io-experimental/photo-slideshow/pull/10

**Comment by Shane01638** [comment]
> Could you try this one: #10

Thank you, could you provide some instruction?

**Comment by Shane01638** [comment]
> Could you try this one: #10

Ok, I figured out how to push the changes you made and it's working now, thank you!
